In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [9]:
df=pd.read_csv('loan_data.csv')
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0

In [10]:
df.describe()

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
count,9578.000000,9578.000000,9578.000000,9578.000000,9578.000000,9578.000000,9578.000000,9.578000e+03,9578.000000,9578.000000,9578.000000,9578.000000,9578.000000
mean,0.804970,0.122640,319.089413,10.932117,12.606679,710.846314,4560.767197,1.691396e+04,46.799236,1.577469,0.163708,0.062122,0.160054
std,0.396245,0.026847,207.071301,0.614813,6.883970,37.970537,2496.930377,3.375619e+04,29.014417,2.200245,0.546215,0.262126,0.366676
min,0.000000,0.060000,15.670000,7.547502,0.000000,612.000000,178.958333,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.103900,163.770000,10.558414,7.212500,682.000000,2820.000000,3.187000e+03,22.600000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.122100,268.950000,10.928884,12.665000,707.000000,4139.958333,8.596000e+03,46.300000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.140700,432.762500,11.291293,17.950000,737.000000,5730.000000,1.824950e+04,70.900000,2.000000,0.000000,0.000000,0.000000
max,1.000000,0.216400,940.140000,14.528354,29.960000,827.000000,17639.958330,1.207359e+06,119.000000,33.000000,13.000000,5.000000,1.000000

In [11]:
df.dtypes

credit.policy          int64
purpose               object
int.rate             float64
installment          float64
log.annual.inc       float64
dti                  float64
fico                   int64
days.with.cr.line    float64
revol.bal              int64
revol.util           float64
inq.last.6mths         int64
delinq.2yrs            int64
pub.rec                int64
not.fully.paid         int64
dtype: object

In [12]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [13]:
df.shape

(9578, 14)

In [14]:
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0

In [15]:
df.purpose.value_counts(normalize=True)*100

purpose
debt_consolidation    41.313427
all_other             24.337022
credit_card           13.176028
home_improvement       6.567133
small_business         6.462727
major_purchase         4.562539
educational            3.581123
Name: proportion, dtype: float64

Tasks:
  
1) **Feature Transformation** : Transform categorical values into numerical values (discrete)

which encoding method to be used for df.purpose columns ?

1) **Label encoding** - it is being used when we have relation between the values and it is not sequential.. E.g. : S , M , L , XL , XXL

2) **One Hot encoding** -  it is being used when we have no relation between the values E.g. - Names of Countries in a column,

In [16]:
df_encoded = pd.get_dummies(df,columns=['purpose'],drop_first=True,dtype=int)  # drop_first -> its also a way to handle multi collinearity problem
df_encoded.head()

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,0,1,0,0,0,0
1,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,1,0,0,0,0,0
2,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,0,1,0,0,0,0
3,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,0,1,0,0,0,0
4,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,1,0,0,0,0,0

**Column name Treatment i.e. replace "." in column names with "_"**

In [19]:
df_encoded.columns

Index(['credit.policy', 'int.rate', 'installment', 'log.annual.inc', 'dti',
       'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='object')

**OPTION 1**

normally Used for renaming All the columns

In [20]:
updates_col_names=[col.replace(".","_") for col in df_encoded.columns]
updates_col_names

['credit_policy',
 'int_rate',
 'installment',
 'log_annual_inc',
 'dti',
 'fico',
 'days_with_cr_line',
 'revol_bal',
 'revol_util',
 'inq_last_6mths',
 'delinq_2yrs',
 'pub_rec',
 'not_fully_paid',
 'purpose_credit_card',
 'purpose_debt_consolidation',
 'purpose_educational',
 'purpose_home_improvement',
 'purpose_major_purchase',
 'purpose_small_business']

In [21]:
df_encoded.columns=updates_col_names
df_encoded.columns

Index(['credit_policy', 'int_rate', 'installment', 'log_annual_inc', 'dti',
       'fico', 'days_with_cr_line', 'revol_bal', 'revol_util',
       'inq_last_6mths', 'delinq_2yrs', 'pub_rec', 'not_fully_paid',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='object')

**OPTION 2**

normally Used for renaming few columns

In [14]:
for col in df_encoded.columns:

  # print(col)
  df_encoded.rename(columns={col:col.replace(".","_")},inplace=True)

df_encoded.columns

Index(['credit_policy', 'int_rate', 'installment', 'log_annual_inc', 'dti',
       'fico', 'days_with_cr_line', 'revol_bal', 'revol_util',
       'inq_last_6mths', 'delinq_2yrs', 'pub_rec', 'not_fully_paid',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='object')

**Exploratory data analysis of different factors in the dataset**

In [22]:
df_encoded.groupby(['not_fully_paid'])['int_rate'].describe()

,count,mean,std,min,25%,50%,75%,max
not_fully_paid,,,,,,,,
0,8045.0,0.120770,0.026692,0.0600,0.0996,0.1218,0.1387,0.2121
1,1533.0,0.132452,0.025495,0.0705,0.1154,0.1316,0.1482,0.2164

In [36]:
df_encoded.groupby([pd.cut(df_encoded['int_rate'],bins=10)])['not_fully_paid'].describe()

                   count      mean       std  min  25%  50%  75%  max
int_rate
(0.0598, 0.0756]   256.0  0.039062  0.194123  0.0  0.0  0.0  0.0  1.0
(0.0756, 0.0913]  1218.0  0.059934  0.237463  0.0  0.0  0.0  0.0  1.0
(0.0913, 0.107]   1090.0  0.122018  0.327457  0.0  0.0  0.0  0.0  1.0
(0.107, 0.123]    2254.0  0.149956  0.357107  0.0  0.0  0.0  0.0  1.0
(0.123, 0.138]    2117.0  0.177137  0.381875  0.0  0.0  0.0  0.0  1.0
(0.138, 0.154]    1577.0  0.205453  0.404161  0.0  0.0  0.0  0.0  1.0
(0.154, 0.169]     627.0  0.240829  0.427928  0.0  0.0  0.0  0.0  1.0
(0.169, 0.185]     302.0  0.291391  0.455157  0.0  0.0  0.0  1.0  1.0
(0.185, 0.201]     100.0  0.280000  0.451261  0.0  0.0  0.0  1.0  1.0
(0.201, 0.216]      37.0  0.351351  0.483978  0.0  0.0  0.0  1.0  1.0

In [42]:
df_encoded.groupby([pd.cut(df_encoded['fico'],bins=10)])['int_rate'].mean()

fico
(611.785, 633.5]    0.161192
(633.5, 655.0]      0.152144
(655.0, 676.5]      0.150165
(676.5, 698.0]      0.134450
(698.0, 719.5]      0.122800
(719.5, 741.0]      0.109147
(741.0, 762.5]      0.099584
(762.5, 784.0]      0.090677
(784.0, 805.5]      0.091565
(805.5, 827.0]      0.093428
Name: int_rate, dtype: float64

In [38]:
df_encoded.groupby([pd.cut(df_encoded['fico'],bins=10),pd.cut(df_encoded['int_rate'],bins=5)])['not_fully_paid'].describe()

                                    count      mean       std  min  25%  50%  \
fico             int_rate
(611.785, 633.5] (0.123, 0.154]       4.0  0.500000  0.577350  0.0  0.0  0.5
                 (0.154, 0.185]       8.0  0.500000  0.534522  0.0  0.0  0.5
(633.5, 655.0]   (0.0598, 0.0913]     1.0  0.000000       NaN  0.0  0.0  0.0
                 (0.123, 0.154]     221.0  0.289593  0.454603  0.0  0.0  0.0
                 (0.154, 0.185]     114.0  0.350877  0.479352  0.0  0.0  0.0
                 (0.185, 0.216]      14.0  0.142857  0.363137  0.0  0.0  0.0
(655.0, 676.5]   (0.0598, 0.0913]     2.0  0.000000  0.000000  0.0  0.0  0.0
                 (0.0913, 0.123]     72.0  0.180556  0.387349  0.0  0.0  0.0
                 (0.123, 0.154]     792.0  0.214646  0.410836  0.0  0.0  0.0
                 (0.154, 0.185]     434.0  0.251152  0.434176  0.0  0.0  0.0
                 (0.185, 0.216]      74.0  0.324324  0.471317  0.0  0.0  0.0
(676.5, 698.0]   (0.0598, 0.0913]     3.0  0.000000  0.000000  0.0  0.0  0.0
                 (0.0913, 0.123]    609.0  0.208539  0.406598  0.0  0.0  0.0
                 (0.123, 0.154]    1598.0  0.160826  0.367485  0.0  0.0  0.0
                 (0.154, 0.185]     241.0  0.215768  0.412210  0.0  0.0  0.0
                 (0.185, 0.216]      34.0  0.294118  0.462497  0.0  0.0  0.0
(698.0, 719.5]   (0.0598, 0.0913]    39.0  0.102564  0.307355  0.0  0.0  0.0
                 (0.0913, 0.123]    908.0  0.150881  0.358130  0.0  0.0  0.0
                 (0.123, 0.154]     703.0  0.174964  0.380207  0.0  0.0  0.0
                 (0.154, 0.185]      74.0  0.243243  0.431969  0.0  0.0  0.0
                 (0.185, 0.216]      11.0  0.272727  0.467099  0.0  0.0  0.0
(719.5, 741.0]   (0.0598, 0.0913]   270.0  0.103704  0.305442  0.0  0.0  0.0
                 (0.0913, 0.123]    866.0  0.123557  0.329265  0.0  0.0  0.0
                 (0.123, 0.154]     227.0  0.224670  0.418287  0.0  0.0  0.0
                 (0.154, 0.185]      28.0  0.214286  0.417855  0.0  0.0  0.0
                 (0.185, 0.216]       1.0  1.000000       NaN  1.0  1.0  1.0
(741.0, 762.5]   (0.0598, 0.0913]   560.0  0.051786  0.221792  0.0  0.0  0.0
                 (0.0913, 0.123]    585.0  0.099145  0.299113  0.0  0.0  0.0
                 (0.123, 0.154]      96.0  0.229167  0.422503  0.0  0.0  0.0
                 (0.154, 0.185]      26.0  0.346154  0.485165  0.0  0.0  0.0
                 (0.185, 0.216]       2.0  0.000000  0.000000  0.0  0.0  0.0
(762.5, 784.0]   (0.0598, 0.0913]   351.0  0.037037  0.189122  0.0  0.0  0.0
                 (0.0913, 0.123]    175.0  0.097143  0.297002  0.0  0.0  0.0
                 (0.123, 0.154]      29.0  0.275862  0.454859  0.0  0.0  0.0
                 (0.154, 0.185]       3.0  0.333333  0.577350  0.0  0.0  0.0
(784.0, 805.5]   (0.0598, 0.0913]   196.0  0.035714  0.186052  0.0  0.0  0.0
                 (0.0913, 0.123]     95.0  0.115789  0.321670  0.0  0.0  0.0
                 (0.123, 0.154]      20.0  0.100000  0.307794  0.0  0.0  0.0
                 (0.154, 0.185]       1.0  0.000000       NaN  0.0  0.0  0.0
                 (0.185, 0.216]       1.0  1.000000       NaN  1.0  1.0  1.0
(805.5, 827.0]   (0.0598, 0.0913]    52.0  0.038462  0.194184  0.0  0.0  0.0
                 (0.0913, 0.123]     34.0  0.029412  0.171499  0.0  0.0  0.0
                 (0.123, 0.154]       4.0  0.000000  0.000000  0.0  0.0  0.0

                                    75%  max
fico             int_rate
(611.785, 633.5] (0.123, 0.154]    1.00  1.0
                 (0.154, 0.185]    1.00  1.0
(633.5, 655.0]   (0.0598, 0.0913]  0.00  0.0
                 (0.123, 0.154]    1.00  1.0
                 (0.154, 0.185]    1.00  1.0
                 (0.185, 0.216]    0.00  1.0
(655.0, 676.5]   (0.0598, 0.0913]  0.00  0.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    0.75  1.0
                 (0.185, 0.216]    1.00  1.0
(676.5, 698.0]   (0.0598, 0.0913]  0.00  0.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    0.00  1.0
                 (0.185, 0.216]    1.00  1.0
(698.0, 719.5]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    0.00  1.0
                 (0.185, 0.216]    0.50  1.0
(719.5, 741.0]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    0.00  1.0
                 (0.185, 0.216]    1.00  1.0
(741.0, 762.5]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    1.00  1.0
                 (0.185, 0.216]    0.00  0.0
(762.5, 784.0]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    1.00  1.0
                 (0.154, 0.185]    0.50  1.0
(784.0, 805.5]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  1.0
                 (0.154, 0.185]    0.00  0.0
                 (0.185, 0.216]    1.00  1.0
(805.5, 827.0]   (0.0598, 0.0913]  0.00  1.0
                 (0.0913, 0.123]   0.00  1.0
                 (0.123, 0.154]    0.00  0.0

In [35]:
df_encoded.groupby([pd.cut(df_encoded['int_rate'],bins=10)])['not_fully_paid'].value_counts()

int_rate          not_fully_paid
(0.0598, 0.0756]  0                  246
                  1                   10
(0.0756, 0.0913]  0                 1145
                  1                   73
(0.0913, 0.107]   0                  957
                  1                  133
(0.107, 0.123]    0                 1916
                  1                  338
(0.123, 0.138]    0                 1742
                  1                  375
(0.138, 0.154]    0                 1253
                  1                  324
(0.154, 0.169]    0                  476
                  1                  151
(0.169, 0.185]    0                  214
                  1                   88
(0.185, 0.201]    0                   72
                  1                   28
(0.201, 0.216]    0                   24
                  1                   13
Name: count, dtype: int64

In [23]:
df_encoded.groupby(['not_fully_paid'])['pub_rec'].describe()

                 count      mean       std  min  25%  50%  75%  max
not_fully_paid
0               8045.0  0.056557  0.255537  0.0  0.0  0.0  0.0  5.0
1               1533.0  0.091324  0.292659  0.0  0.0  0.0  0.0  2.0

In [25]:
df_encoded.groupby(['not_fully_paid'])['fico'].describe()

,count,mean,std,min,25%,50%,75%,max
not_fully_paid,,,,,,,,
0,8045.0,713.326911,38.223723,612.0,682.0,707.0,742.0,827.0
1,1533.0,697.828441,33.756808,617.0,672.0,692.0,717.0,822.0

In [26]:
df_encoded['fico'].describe()

count    9578.000000
mean      710.846314
std        37.970537
min       612.000000
25%       682.000000
50%       707.000000
75%       737.000000
max       827.000000
Name: fico, dtype: float64

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
df_encoded.groupby([pd.cut(df_encoded['fico'],bins=10)])['not_fully_paid'].describe()

                   count      mean       std  min  25%  50%  75%  max
fico
(611.785, 633.5]    12.0  0.500000  0.522233  0.0  0.0  0.5  1.0  1.0
(633.5, 655.0]     350.0  0.302857  0.460152  0.0  0.0  0.0  1.0  1.0
(655.0, 676.5]    1374.0  0.229985  0.420976  0.0  0.0  0.0  0.0  1.0
(676.5, 698.0]    2485.0  0.179477  0.383828  0.0  0.0  0.0  0.0  1.0
(698.0, 719.5]    1735.0  0.164265  0.370623  0.0  0.0  0.0  0.0  1.0
(719.5, 741.0]    1392.0  0.138649  0.345705  0.0  0.0  0.0  0.0  1.0
(741.0, 762.5]    1269.0  0.092987  0.290528  0.0  0.0  0.0  0.0  1.0
(762.5, 784.0]     558.0  0.069892  0.255194  0.0  0.0  0.0  0.0  1.0
(784.0, 805.5]     313.0  0.067093  0.250583  0.0  0.0  0.0  0.0  1.0
(805.5, 827.0]      90.0  0.033333  0.180511  0.0  0.0  0.0  0.0  1.0

In [28]:
df_encoded.head()

,credit_policy,int_rate,installment,log_annual_inc,dti,fico,days_with_cr_line,revol_bal,revol_util,inq_last_6mths,delinq_2yrs,pub_rec,not_fully_paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,0,1,0,0,0,0
1,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,1,0,0,0,0,0
2,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,0,1,0,0,0,0
3,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,0,1,0,0,0,0
4,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,1,0,0,0,0,0

In [31]:
df_encoded.corr()[['not_fully_paid']].sort_values(by='not_fully_paid',ascending=False)

                            not_fully_paid
not_fully_paid                    1.000000
int_rate                          0.159552
inq_last_6mths                    0.149452
purpose_small_business            0.084460
revol_util                        0.082088
revol_bal                         0.053699
installment                       0.049955
pub_rec                           0.048634
dti                               0.037362
purpose_educational               0.021609
delinq_2yrs                       0.008881
purpose_home_improvement          0.007272
purpose_debt_consolidation       -0.017543
purpose_major_purchase           -0.028580
days_with_cr_line                -0.029237
log_annual_inc                   -0.033439
purpose_credit_card              -0.047136
fico                             -0.149666
credit_policy                    -0.158119

In [43]:
df_encoded.groupby([df_encoded['credit_policy']])['not_fully_paid'].describe()

                count      mean       std  min  25%  50%  75%  max
credit_policy
0              1868.0  0.277837  0.448053  0.0  0.0  0.0  1.0  1.0
1              7710.0  0.131518  0.337987  0.0  0.0  0.0  0.0  1.0